name: ManyLinux build (x86_64)
inputs:
  python-tag:
    required: true
runs:
    using: 'docker'
    image: docker://quay.io/pypa/manylinux2014_x86_64
    args:
        - .github/workflows/entrypoint.sh
        - ${{ inputs.python-tag }}
