name: Build bundle

on:
  push:
    branches:
      - lambdadog/fugashi-bundled
  create:

jobs:
  build_windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        include:
        - python-version: '3.7'
          py-short: '37'
          py-short2: '37m'
        - python-version: '3.8'
          py-short: '38'
          py-short2: '38'
        - python-version: '3.9'
          py-short: '39'
          py-short2: '39'
        - python-version: '3.10'
          py-short: '310'
          py-short2: '310'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache mecab
      id: cache-mecab
      uses: actions/cache@v1
      with:
        path: C:/mecab
        key: mecab-windows
    - name: Download mecab
      if: steps.cache-mecab.outputs.cache-hit != 'true'
      shell: bash
      run: |
        curl -LO "https://github.com/chezou/mecab/releases/download/mecab-0.996-msvc-5/mecab-msvc-x64.zip"
        unzip -o "mecab-msvc-x64.zip" -d c:/mecab
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools wheel pip setuptools-scm
        pip install -r requirements.txt
    - name: Build PyExt
      run: |
        python setup.py build
    - name: Prepare for upload
      shell: bash
      run: |
        mkdir -p upload/mecab
        mv build/lib.*/fugashi/fugashi.*.pyd upload/
        # TODO: Add noise to dll name
        mv c:/mecab/libmecab.dll upload/mecab
    - uses: actions/upload-artifact@v1
      with:
        name: bundle
        path: upload
  build_macos:
    runs-on: macos-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        include:
        - python-version: '3.7'
          py-short: '37'
          py-short2: '37m'
        - python-version: '3.8'
          py-short: '38'
          py-short2: '38'
        - python-version: '3.9'
          py-short: '39'
          py-short2: '39'
        - python-version: '3.10'
          py-short: '310'
          py-short2: '310'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Cache mecab
      id: cache-mecab
      uses: actions/cache@v1
      with:
        path: mecab-out
        key: mecab-macos
    - name: Build mecab
      shell: bash
      run: |
        git clone --depth=1 https://github.com/taku910/mecab.git
        cd mecab/mecab
        ./configure --enable-utf8-only --prefix=${GITHUB_WORKSPACE}/mecab-out
        make
        make install
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools wheel pip setuptools-scm
        pip install -r requirements.txt
    - name: Build PyExt
      run: |
        # Add mecab-config to path
        export PATH=$PATH:$PWD/mecab-out/bin

        python setup.py build
    - name: Prepare for upload
      shell: bash
      run: |
        mkdir -p upload/mecab
        mv build/lib.*/fugashi/fugashi.*.so upload/
        mv mecab-out/lib/libmecab.2.dylib upload/mecab/libmecab.dylib
    - uses: actions/upload-artifact@v1
      with:
        name: bundle
        path: upload
