name: Build manylinux1 wheels

on:
  push:
    branches: 
      - lambdadog/fugashi-bundled
  create:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: ./.github/workflows/actions/build-manylinux/
    - name: Upload Wheels
      uses: actions/upload-artifact@v1
      with: 
        name: manylinux2014-wheels
        path: manylinux2014-wheels

  build_linux-aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - uses: ./.github/workflows/actions/build-manylinux-aarch64/
    - name: Upload Wheels
      uses: actions/upload-artifact@v1
      with:
        name: manylinux-aarch64-wheels
        path: manylinux-aarch64-wheels
